### ISSUE TITLE
array index -1 error

### ISSUE THREAD

**Issue by alanruttenberg** [WarrenWilkinson/read-csv#4]
This is in ABCL. Small file triggering it attached. Looks ok to me. Some ABCL peculiarity?
```
Invalid index -1 for array org.armedbear.lisp.SimpleArray_T@1fa55ae6.
   [Condition of type PROGRAM-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Abort thread.

Backtrace:
  0: (INVOKE-DEBUGGER #<PROGRAM-ERROR {34AE255D}>)
  1: org.armedbear.lisp.Lisp.error(Lisp.java:382)
  2: org.armedbear.lisp.Lisp.program_error(Lisp.java:440)
  3: org.armedbear.lisp.SimpleArray_T.getRowMajorIndex(SimpleArray_T.java:278)
  4: (AREF #3A(((READ-CSV::NOOP 0) (READ-CSV::SHIP 1) (READ-CSV::SHIP -1) (READ-CSV::NOOP 3) (READ-CSV::NEXT 0) (READ-CSV::ADDC 2)) ..) -1 5 0)
  5: (READ-CSV:READ-CSV #<FILE-STREAM {414FB381}> #\, NIL :EOF)
  6: (READ-CSV:PARSE-CSV #<FILE-STREAM {414FB381}>)
  7: (SYSTEM::%EVAL (WITH-OPEN-FILE (F "~/Desktop/small.txt") (READ-CSV:PARSE-CSV F)))
  8: (EVAL (WITH-OPEN-FILE (F "~/Desktop/small.txt") (READ-CSV:PARSE-CSV F)))
```
[small.txt](https://github.com/WarrenWilkinson/read-csv/files/2406864/small.txt)

**Comment by g000001** [comment]
Thank you for your PR https://github.com/WarrenWilkinson/read-csv/pull/5 .

I could reproducing the error with ABCL 1.5.0 and fixing the error by your PR.

IMHO It maybe a ABCL's constant variable optimazation bug or something.
But, Using `eql` rather than `eq` is much conformable to spec.

http://l1sp.org/cl/eq
> An implementation is permitted to make ``copies'' of characters and numbers at any time. The effect is that Common Lisp makes no guarantee that eq is true even when both its arguments are ``the same thing'' if that thing is a character or number.
